apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: webserver3
  name: webserver3
spec:
  containers:
  - image: httpd
    name: webserver3
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
